project_id = "hgocaleuiywlfuyclcco"

[functions.send-campaign]
verify_jwt = true

[functions.generate-email-html]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.send-waiting-list-confirmation]
verify_jwt = false
